export interface Bairro {
  cras: string;
  bairro: Array<string>;
}

export const BairroCras: Bairro[] = [
  {
    cras: 'Codin',
    bairro: [
      'CODIN',
      'JARDIM BOA VISTA',
      'LAGOA DAS PEDRAS',
      'NOVO ELDORADO',
      'PARQUE ELDORADO',
      'PARQUE JARDIM AEROPORTO',
      'PARQUE JARDIM CEASA',
      'PARQUE SANTOS DUMONT',
      'PARQUE SÃO SILVESTRE',
      'TERRA PROMETIDA',
      'VILA INDUSTRIAL',
      'KM 5 a 8',
    ],
  },

  {
    cras: 'Custodópolis',
    bairro: [
      'PARQUE BANDEIRANTES',
      'PARQUE BARAO DO RIO BRANCO',
      'PARQUE BONSUCESSO',
      'PARQUE CUSTODOPOLIS',
      'PARQUE NOVA CAMPOS',
      'PARQUE NOVO MUNDO',
      'PARQUE SANTA CLARA',
      'PARQUE SANTA ROSA',
      'PARQUE SÃO DOMINGOS',
      'RESIDENCIAL PLANICIE',
      'COND SANTA ROSA',
      'COND SANTA ROSA 2',
      'COND. DOS NOGUEIRAS',
    ],
  },

  {
    cras: 'Jardim Carioca',
    bairro: [
      'PARQUE ALVORADA',
      'JARDIM CARIOCA',
      'PARQUE NITEROI',
      'PARQUE PRAZERES',
      'PARQUE PRESIDENTE VARGAS',
      'PARQUE RESIDENCIAL DA LAPA II',
      'PARQUE SANTO ANTONIO',
      'PARQUE VICENTE GONÇALVES DIAS',
      'ZUZA MOTA',
      'USINA SÃO JOAO',
    ],
  },

  {
    cras: 'Esplanada',
    bairro: [
      'CAJU',
      'ITERERE',
      'MORANGABA',
      'PARQUE CORRIENTES',
      'PARQUE DOM BOSCO',
      'PARQUE DOS RODOVIÁRIOS',
      'PARQUE ESPLANADA',
      'JARDIM MARIA DE QUEIROZ',
      'PARQUE JULIAO NOGUEIRA',
      'PARQUE LEOPOLDINA',
      'NOSSA SRA DO ROSARIO',
      'NOVA BRASILIA',
      'PECUARIA',
      'PARQUE SANTO AMARO',
      'PARQUE SÃO CAETANO',
      'PARQUE SUMARE',
      'PARQUE TAMANDARE',
      'SANTA CRUZ',
      'CENTRO (OU ESPLANADA)',
    ],
  },

  {
    cras: 'Chatuba',
    bairro: [
      'CARVAO',
      'CHATUBA',
      'FAZENDINHA',
      'JOAO MARIA',
      'PARQUE ALPHAVILLE',
      'PARQUE ALPHAVILLE II',
      'PARQUE AURORA',
      'PARQUE CARLOS DE LACERDA',
      'PARQUE DR BEDA',
      'PARQUE IPS',
      'PARQUE JOAO SEIXAS',
      'PARQUE ROSARIO',
      'PARQUE RUI BARBOSA',
      'PARQUE SÃO BENEDITO',
      'PARQUE SÃO LINO',
      'CANTAGALO',
      'CAPAO',
      'PARQUE FAZENDA GRANDE',
    ],
  },

  {
    cras: 'Matadouro',
    bairro: [
      'CHACARA JOAO FERREIRA',
      'HORTO',
      'JARDIM FLAMBOYANT I',
      'JARDIM FLAMBOYANT II',
      'LAPA',
      'MATADOURO',
      'PARQUE CALIFORNIA',
      'PARQUE OLIVEIRA BOTELHO',
      'PARQUE RIACHUELO',
      'PARQUE SALO BRAND',
      'PARQUE TURF CLUB',
      'CENTRO (OU MATADOURO',
      'TIRA GOSTO',
    ],
  },

  {
    cras: 'Penha',
    bairro: [
      'COND CIDADE VERDE',
      'ESTANCIA DA PENHA',
      'FAZENDINHA',
      'PARQUE ANGELICA',
      'PENHA',
      'PARQUE BELA VISTA',
      'PARQUE IMPERIAL',
      'PARQUE JOSE DO PATROCINIO',
      'PARQUE TROPICAL',
      'PARQUE CONJ. SANTA MARIA',
      'PARQUE DO PRADO',
      'PARQUE JD DAS ACACIAS',
      'PARQUE RES SANTO ANTONIO',
      'PARQUE RES PORTO SEGURO',
      'PARQUE TARCISIO MIRANDA',
      'PARQUE VARANDA DO VISCONDE',
      'PARQUE VILA MENEZES',
      'PARQUE VILA VERDE',
      'RES. VIVENDAS DA PENHA I',
      'RES. VIVENDAS DA PENHA II',
      'SOLAR DA PENHA',
      'USINA SANTO ANTONIO',
      'VILA MANHAES',
      'VIVENDAS DOS COQUEIROS',
      'VIVENDAS DOS COQUEIROS II',
    ],
  },

  {
    cras: 'Goitacazes',
    bairro: [
      'ALTO DA AREIA',
      'ALTO DO ELISEU',
      'BALTAZAR',
      'BARRA DO JACARE',
      'BEIRA DO FAZ',
      'BEIRA DO TAI',
      'BUGALHO',
      'CABOIO',
      'CAMPO LIMPO',
      'CANAL DAS FLEXAS',
      'CANTO DO ENGENHO',
      'CANTO DO RIO TOCOS',
      'CARIOCA DE TOCOS',
      'CAXIAS DE TOCOS',
      'CAZUMBA',
      'COQUEIRO DE TOCOS',
      'CORRENTEZA',
      'CUPIM DE POÇO GORDO',
      'DONANA',
      'ESPINHO',
      'GAIVOTAS',
      'GOIABA',
      'GOITACAZES',
      'JARDIM PARAISO DE TOCOS',
      'JARDIM PRIMAVERA',
      'LINHA DO LIMÃO',
      'MARCELO',
      'MINEIROS',
      'MONTENEGRO',
      'MUTEMA',
      'NOVA GOITACAZES',
      'PARQUE REAL',
      'PARQUE SÃO SILVANO',
      'PARQUE SARAIVA',
      'PARQUE TRANSMISSOR',
      'PAUS AMARELOS',
      'POÇO GORDO',
      'PONTA GROSSA',
      'PONTO DE COQUEIROS',
      'PONTO DO CARMO',
      'SABAO',
      'SATURNINO BRAGA',
      'SÃO MARTINHO',
      'SÃO SEBASTIÃO',
      'TOCAIA',
      'VALA DO MATO',
      'TOCOS',
      'VILA REAL',
      'VILA ROMANA',
    ],
  },

  {
    cras: 'Parque Guarus',
    bairro: [
      'INVASÃO CIDADE LUZ',
      'BOA VISTA',
      'PARQUE ALDEIA',
      'PARQUE ALDEIA I',
      'PARQUE ALDEIA II',
      'PARQUE CIDADE LUZ',
      'PARQUE FUNDAO',
      'PARQUE GUARUS',
      'PARQUE JD GUARUS',
      'PARQUE LEBRET',
      'PARQUE SANTA HELENA',
      'PARQUE SÃO MATHEUS',
      'PARQUE SÃO JOSE',
      'PARQUE VERA CRUZ',
      'SAPUCAIA',
      'TRES VENDAS',
    ],
  },

  {
    cras: 'Travessão',
    bairro: [
      'BALANCA RANGEL',
      'BREJO GRANDE',
      'CAMPELO',
      'CANAA',
      'CAXETA',
      'GUANDU',
      'MATUTU',
      'MUNDEOS',
      'NOVA CANAA',
      'RIBEIRO DO AMARO',
      'SANTANA',
      'TRAVESSÃO',
      'SÃO DIOGO',
      'ESCOVA URUBU',
      'KM 9 a 16',
    ],
  },

  {
    cras: 'Morro do Coco',
    bairro: [
      'AREIA BRANCA',
      'CHAVE DO PARAISO',
      'CONSELHEIRO JOSINO',
      'ESPIRITO SANTINHO',
      'MATA DA CRUZ',
      'MORRO DO COCO',
      'MURUNDU',
      'PALMARES',
      'SANTA BARBARA',
      'SANTA MARIA',
      'SANTO EDUARDO',
      'SÃO LUIS DE MUTUCA',
      'SÃO ROQUE',
      'SESMARIA',
      'VILA NOVA',
      'DIVISA',
    ],
  },
  {
    cras: 'Farol',
    bairro: [
      'BABOSA',
      'BAIXA GRANDE',
      'BOA VISTA',
      'CAMPO DE AREIA',
      'CIPRIAO',
      'CORREGO FUNDO',
      'FAROL DE SÃO THOME',
      'FAROLZINHO',
      'LAGAMAR',
      'LARGO DO GARCIA',
      'MARRECAS',
      'MULACO',
      'MUSSUREPE',
      'PARQUE MOSTEIRO DE SÃO BENTO',
      'PARQUE NAUTICO',
      'PITANGUEIRA',
      'QUIXABA',
      'RADIO VELHO',
      'RETIRO',
      'SANTO AMARO DE CAMPOS',
      'TERMINAL PESQUEIRO',
      'VEIGA',
      'VIEGAS',
      'VILA DO SOL',
      'VILA DOS PESCADORES',
      'XEXE',
    ],
  },

  {
    cras: 'Jockey',
    bairro: [
      'JOCKEY CLUB',
      'NOVO JOCKEY',
      'JOCKEY I',
      'JOCKEY II',
      'BENTA PEREIRA',
      'VISTA ALEGRE',
      'MORADO DO ORIENTE',
      'CAMBAIBA',
      'CAMPO NOVO',
      'MARTINS LAGE',
      'VENDA NOVA',
    ],
  },

  {
    cras: 'Ururaí',
    bairro: [
      'ACAMP SEM TERRA ESTRADA LEITE',
      'ASSENT ALELUIA',
      'ASSENT ANTONIO FARIAS',
      'ASSENT BATATAL',
      'ASSENT CAMBUCA',
      'ASSENT TERRA CONQUISTADA',
      'CEREJEIRA',
      'CONCEICAO DO IMBE',
      'DORES DE MACABU',
      'GURIRI',
      'IBITIOCA',
      'IMBE',
      'LAGOA DE CIMA',
      'MACACO',
      'MATO ESCURO',
      'MORRO GRANDE',
      'PEDRA NEGRA',
      'PERNAMBUCA',
      'PLANICIE',
      'PONTA DA LAMA',
      'QUILOMBO',
      'SENTINELA DO IMBE',
      'SERRINHA',
      'TAPERA',
      'URURAI',
      'VIANA',
    ],
  },
];
